default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  port: 3306
  socket:  /run/mysqld/mysqld.sock   # Only needed if MySQL socket is in a non-default location

development:
  <<: *default
  database: shopping_rails

test:
  <<: *default
  database: shopping_rails_test

production:
  <<: *default
  database: shopping_rails_production